import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Marquee from "@/components/Marquee";
import { ToastContainer } from "react-toastify";

const notoSerifBangali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBangali.className} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <Header></Header>
        <Marquee></Marquee>
        <main className="flex-1">
          {children}
        </main>
        <Footer></Footer>

        <ToastContainer
          position="top-center"
          autoClose={3000}
        />
      </body>
    </html>
  );
}
